apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: product-a
  description: The product-a product area
spec:
  type: product-area
  profile:
    displayName: product-a
    email: product-a@example.com
  children: []