# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: betav3-sample-1
  title: Test custom template
  description: test custom actions
spec:
    owner: user:guest
    type: service
    parameters:
    - title: Provie Argo Wft data
      required:
        - namespace
        - workflowTemplateName
        - workflowInputs
      properties:
        namespace:
            title: K8s Namespace
            type: string
            default: argo
            maxLength: 8
            description: Namespace to subit wf
            ui:autofocus: true
            ui:help: 'Hint: Your app namespace...'
        workflowTemplateName:
            title: Template name
            type: string
            description: Argo workflow template name
            ui:autofocus: true
            default: workflow-template-submittable
            enum:
                - workflow-template-submittable
                - workflow-template-inner-dag
            enumNames:
                - 'hello world'
                - 'dag-sample'
        workflowInputs:
            title: Workflow Inputs
            type: string
            description: Insert key=value argo inputs separated by commas
            ui:widget: textarea
            ui:options:
                rows: 8
            ui:placeholder: ""
    steps:
    - id: submit-wft
      name: Submit WFT
      action: argo:wft:submit
      input:
        namespace: ${{ parameters.namespace }}
        workflowTemplateName: ${{ parameters.workflowTemplateName }}