kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-example-sa
rules:
# Permissions for every EventListener deployment to function
- apiGroups: ["tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates", "tasks", "taskruns"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-sa-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-example-sa
subjects:
- kind: ServiceAccount
  name: tekton-sa
  namespace: default
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: print-task
spec:
  inputs:
    params:
      - name: data
        type: string
        description: print message
        default: test-message
  steps:
    - name: echo-something
      image: ubuntu
      command:
        - echo
      args:
        - "$(inputs.data.message)"
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sink-pipeline
spec:
  params:
  - name: data
    type: string
    default: test-pipeline-message
  tasks:
    - name: print-1
      taskRef:
        name: print-task
      params:
        - name: data
          value: $(params.data)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
  - name: data
    value: $(body.message)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
  - name: data
    description: message
    default: DEFALT MESSAGE VALUE
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: pipeline-template
    spec:
      pipelineRef:
        name: sink-pipeline
      params:
      - name: data
        value: $(params.data)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pipeline-listener
spec:
  serviceAccountName: tekton-sa
  triggers:
    - name: foo-trig
      # interceptor:
      #     objectRef:
      #       apiVersion: v1
      #       kind: Service
      #       name: knative-consumer
      #       namespace: default
      binding:
        name: pipeline-binding
      template:
        name: pipeline-template
      # params:
      # - name: message
      #   value: Hello from the Triggers EventListener!