apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-print-message
spec:
  entrypoint: print-message
  serviceAccountName: argo-workflow
  arguments:
    parameters:
    - name: message
  templates:
  - name: print-message
    inputs:
      parameters:
      - name: message
        value: "{{workflow.parameters.message}}"
    container:
      image: busybox
      command: [echo]
      args: ["{{inputs.parameters.message}}"]